theme: minima
title: The Depths of Deep learning
author: Jonathan Enudeme
email: twoejoe5@gmail.com
description: This is not the regular blog you find the regular stuff. This is a deeper kind of blog where you can learn Deep learning at the surface.

# social links
twitter_username: joe_famouze # DO NOT include the @ character, or else the build will fail!
github_username:  github.com/Joefamouze # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
